environment: ovh
keycloak:
  enabled: true
  global:
    compatibility:
      openshift:
        adaptSecurityContext: auto
  auth:
    adminUser: admin
    adminPassword: "admin"
  cache:
    enabled: false
  containerPorts:
    http: 8080
    https: 8443
    infinispan: 7800
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
  ingress:
    apiVersion: ''
    enabled: true
    hostname: apim-canel-keycloak.apps.app1.numerique-interieur.com
    ingressClassName: ''
    path: /
    pathType: Prefix
    annotations: {}
    selfSigned: false
    servicePort: http
    tls: false
  livenessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 900
    periodSeconds: 90
    successThreshold: 1
    timeoutSeconds: 90
  logging:
    level: INFO
    output: default
  podSecurityContext:
    enabled: false
    fsGroup: null
  externalDatabase:
    existingSecret: "mi-apimcanel-dev-postgres-infra-6293-cluster-app"
    existingSecretHostKey: "host"
    existingSecretPortKey: "port"
    existingSecretUserKey: "username"
    existingSecretDatabaseKey: "dbname"
    existingSecretPasswordKey: "password"
  postgresql:
    enabled: false  
  production: false
  proxy: edge
  replicaCount: 1
  keycloakConfigCli:
    enabled: true
    command:
      - java
      - -jar
      - /opt/bitnami/keycloak-config-cli/keycloak-config-cli-23.0.7.jar
    image:
      registry: docker.io
      repository: bitnami/keycloak-config-cli
      tag: 5.11.1-debian-12-r0
      digest: ""
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 250m
        memory: 206Mi
      limits:
        cpu: 1000m
        memory: 512Mi    
    extraEnvVars:
      - name: IMPORT_VARSUBSTITUTION_ENABLED
        value: "true"
      - name: CLIENTSECRET
        value: "PouetPouet1!"
      - name: CLIENTID
        value: "krakend-client"
      - name: REALM
        value: "krakend-realm"
    existingConfigmap: "keycloak-realm-config"
    cleanupAfterFinished:
      enabled: false
      seconds: 600
  networkPolicy:
    enabled: false
