apiVersion: ENC[AES256_GCM,data:76dqTaC8yrhVIftXIVaFnwErYn9ZTUvVD4bv,iv:gnG/sof/21ZAjTPuYBpzAT3/gkawbC0XlFgJnCQLtXc=,tag:Ms/VVvTTY1dZ6wwmUrhoHA==,type:str]
kind: ENC[AES256_GCM,data:v8m1/xN+ExJCXQ==,iv:cIa2vobu2WJ5LzHmcpBC+TF+6gR/c4410kD4oHXvSpI=,tag:AU4JnNwJJjO4efdeWM0SEg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:x4EOzO2gL1sHL+45pQ==,iv:DvqLXOr3hv8q93RF/Y40Hl1cVOkuTT5T83ZnJjR+7K8=,tag:zoNOLumjwbNW+t66wkgEpg==,type:str]
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:fUO0kWNSZdTm7xk=,iv:yKP1O0wKnysDfvFR/UB/ioHBLK3CQ870i2m7Cg8OtUI=,tag:7//3SauYsNHUxcv0EhUqYQ==,type:str]
          stringData:
            user: ENC[AES256_GCM,data:HfNkCNA=,iv:6ZI0JAoy/ebr3IXhXpd4mhfaITVppkqw4Xw8m5q1AQQ=,tag:AgJ56BKxBpR+DrpaZJ3GFw==,type:str]
            password: ENC[AES256_GCM,data:dTTJcq8=,iv:VO0S7IROw4D6tTVnoWoTvGg56Ew30QoXobgCBxVYt70=,tag:VICKsB7OIo0q//yb1us4Rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g867s7tcftkgkdraz3ezs8xk5c39x6l4thhekhp9s63qxz0m7cgs5kan9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdWt0anE4b0MvSEN4Q29K
            VlZIcHFtQWFTK2ZLUzhKbWJwUEVqbXEzWFFnCmdKcnMwTmprZ09iMWpubmd1NWZY
            TDJ1bXpLUVZvRWQrOHNhdmZLY29WTGMKLS0tIGNHMlNPWFd1NEEyUzgwMzkrcE53
            WWVBN3NyTE9xSFBmQW9YSkNNN0JDcm8KYjwX8saHzEbTFvF0vtPVklzRgy9lbiF4
            d5Ib4Y/W37pbtTeBcuww48DuzsnNl2fGzlHIx6GvIKHr2CsrUzZvIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-09T14:49:22Z"
    mac: ENC[AES256_GCM,data:xVuMxxWAdEltcoUyZD2xGQoMe9qe3P1gdSri4NLba7o6JUueXAAH1B94AP7rhi2uTmXSytILhZoW/qdgyOJ2/W8/qodvRUsXeObQ6kHCuNCEL9WXEBGekX3N9W90Cwc+AxPnof79VF1kYL2TDM7rC/bbIfgzcjcwnAatstJzvAk=,iv:QecTFrFdFleJconZpRI1XoGWL0+zesfelJQq0QvdkcQ=,tag:me6kPRgQvP6n4Xr01fIUHA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
