apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: minio-secrets
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:RgpY5cUWxCjplns=,iv:bOZyZ5SjMUwPM1Vnn7rmKupQCNNby0OjaX3tauESYng=,tag:rG5+ZPonG3o2y+lsIB1+gw==,type:str]
          stringData:
            user: ENC[AES256_GCM,data:ZvLbST8=,iv:gUJZkoSLghrP3xIBdqa9Ufq6WsD2rqQMA7Xu6NH1Gnw=,tag:eeHQmwlVCHubTypqlbnjkg==,type:str]
            password: ENC[AES256_GCM,data:z33ITZB8MpXCKn0n,iv:Seqo/ssUO1luQOD55kZRq/o2ROwfjmCsTPG6tEY8ocM=,tag:5KZQZzshR/9WHHWqOs7vUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g867s7tcftkgkdraz3ezs8xk5c39x6l4thhekhp9s63qxz0m7cgs5kan9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aHROZEkrRlE5TVY3RmU0
            OCtlaU12TFNlSFVCejQ3WU1ZUXM0cWJtZ1E0CjFBZ3l1TzZjQzd5dmxJUXZKTHpR
            TndxRHA3WXhFUFlQYnQyYVBEZUpxem8KLS0tIExuZTd4dWRZRDhtUzhzc2t5Q0tl
            UWVxSlZSSTdMbk4xNHRGenljNkU2aDQKfKH/+SattNdPZRn4/bTXarghwKrhIIRV
            wFMNA0pxuuQTNyvguSvgpZrLkO4flJzNCClnFmEOoVteEZyDVQu9dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-09T15:55:11Z"
    mac: ENC[AES256_GCM,data:x9Wivhd3RME9z5cdpZm4LGE6MHtYORalZcEiBHcxZbh8a6WBtZar3U5nmAyPv9YxSjP3J7xLlrb7n6gvzPfKoKzDynRDkI9vJRriO0OnIRsTCOFRW6jlv599okURdjBDX1AsgH1TrSXGuMxqfStHen3gFVG9fuzzI9uQgQGuEMA=,iv:zVpbpH3QErkPJabv9POpZOAPcb0Zl+uAqZVWKnCobgI=,tag:tf6pb08uFCVmt4upKtw6pg==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.8.1
