nameOverride: ""
fullnameOverride: ""

cluster:
  enabled: true
  nameOverride: ""
  fullnameOverride: ""
  type: postgresql
  mode: standalone

  cluster:
    instances: 1
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []

    storage:
      size: 2Gi
      storageClass: ""

    walStorage:
      size: 1Gi
      storageClass: ""
    postgresUID: 26
    postgresGID: 26
    resources: 
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi

    monitoring:
      enabled: true
      podMonitor:
        enabled: true
      prometheusRule:
        enabled: true
        excludeRules: []

    initdb: 
      database: keycloak
      owner: "keycloak" # Defaults to the database name
      secret:
        name: "" # Name of the secret containing the initial credentials for the owner of the user database. If empty a new secret will be created from scratch
      options: []
      encoding: UTF8

  backups:
    # -- You need to configure backups manually, so backups are disabled by default.
    enabled: false

  pooler:
    # -- Whether to enable PgBouncer
    enabled: false
