apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
data:
  realm-config.yaml: |
    realm: $(REALM)
    enabled: true
    sslRequired: 'none'
    attributes:
      frontendUrl: $(KEYCLOAK_URL)
    clients:
    - clientId: $(CLIENTID)
      enabled: true
      protocol: openid-connect
      serviceAccountsEnabled: true
      surrogateAuthRequired: false
      enabled: true
      alwaysDisplayInConsole: false
      clientAuthenticatorType: client-secret
      secret: $(CLIENTSECRET)
      redirectUris:
        - '*'
      webOrigins:
        - '*'
      notBefore: 0
      bearerOnly: false
      consentRequired: false
      standardFlowEnabled: true
      implicitFlowEnabled: false
      directAccessGrantsEnabled: true
      serviceAccountsEnabled: true
      publicClient: false
      frontchannelLogout: true
      protocol: openid-connect
      attributes:
        oidc.ciba.grant.enabled: 'false'
        client.secret.creation.time: '1712224789'
        backchannel.logout.session.required: 'true'
        display.on.consent.screen: 'false'
        oauth2.device.authorization.grant.enabled: 'false'
        backchannel.logout.revoke.offline.tokens: 'false'
    roles:
      realm:
        - name: "admin"
          description: "Administrator role with full permissions"
          composite: false
          clientRole: false
        - name: "user"
          description: "User role with basic permissions"
          composite: false
          clientRole: false
        - name: "moderator"
          description: "Moderator role with limited permissions"
          composite: false
          clientRole: false
    users:
      - username: admin
        enabled: true
        emailVerified: true
        email: admin@admin.com
        firstName: admin
        lastName: admin
        credentials:
        - type: password
          value: admin
          temporary: false
        realmRoles:
        - admin
      - username: moderator
        enabled: true
        emailVerified: true
        email: moderator@moderator.com
        firstName: moderator
        lastName: moderator        
        credentials:
        - type: password
          value: moderator
          temporary: false
        realmRoles:
        - moderator
      - username: user
        enabled: true
        emailVerified: true
        email: user@user.com
        firstName: user
        lastName: user          
        credentials:
        - type: password
          value: user
          temporary: false
        realmRoles:
        - user
           
